formspree_form_id: formspree_form_id
name: Woocara
title: 1001 Cara Melakukan Apapun
description: 1001 Cara Melakukan Apapun
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
